// Package api provides DJ waveform generation and analysis endpoints.
//
// This file implements:
//   - Waveform peak generation from audio files
//   - DJ analysis caching (waveform data, hot cues)
//   - Waveform data serving via REST API
//
// Waveforms are generated lazily on first request and cached in SQLite.
package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"path/filepath"
	"strings"
	"sync"

	"github.com/ajbergh/viib-mediahub/internal/analysis"
	"github.com/ajbergh/viib-mediahub/internal/analysis/waveformartifact"
	"github.com/ajbergh/viib-mediahub/internal/db"
	"github.com/ajbergh/viib-mediahub/internal/logger"
	"github.com/go-chi/chi/v5"
)

// errClientWaveformRequired marks formats which the browser can decode but the
// server intentionally does not decode. Callers should fall back to Web Audio.
var errClientWaveformRequired = errors.New("client-side waveform generation required")

// WaveformResponse contains the waveform peak data for a track.
type WaveformResponse struct {
	TrackID    string    `json:"trackId"`
	Duration   float64   `json:"duration"`   // Total duration in seconds
	SampleRate int       `json:"sampleRate"` // Source sample rate
	Resolution int       `json:"resolution"` // Samples per peak (e.g., 256)
	Peaks      []float64 `json:"peaks"`      // Normalized peak values (0-1)
}

// HotCue represents a saved position in a track.
type HotCue struct {
	Slot              int      `json:"slot"`     // 1-8
	Position          float64  `json:"position"` // Position in seconds
	Label             string   `json:"label,omitempty"`
	Color             string   `json:"color"` // Hex color code
	Origin            string   `json:"origin,omitempty"`
	GeneratorVersion  string   `json:"generatorVersion,omitempty"`
	Confidence        *float64 `json:"confidence,omitempty"`
	Kind              string   `json:"kind,omitempty"`
	Locked            bool     `json:"locked,omitempty"`
	Rationale         string   `json:"rationale,omitempty"`
	SourceFingerprint string   `json:"sourceFingerprint,omitempty"`
	DownbeatAligned   bool     `json:"downbeatAligned,omitempty"`
	UpdatedAt         int64    `json:"updatedAt,omitempty"`
}

// HotCuesResponse contains hot cue data for a track.
type HotCuesResponse struct {
	TrackID string   `json:"trackId"`
	HotCues []HotCue `json:"hotCues"`
}

// getDJWaveform generates or returns cached waveform data for a track.
// GET /api/dj/waveform/{id}
func (a *API) getDJWaveform(w http.ResponseWriter, r *http.Request) {
	trackID := chi.URLParam(r, "id")
	if trackID == "" {
		respondError(w, http.StatusBadRequest, "Track ID required")
		return
	}

	// Legacy song-ID-only caches cannot prove current source identity.
	source, err := a.resolveAnalysisSource(r.Context(), trackID)
	if err != nil {
		respondError(w, 404, "Track source unavailable")
		return
	}
	artifact, artifactErr := a.db.GetTrackAnalysisArtifact(trackID, waveformartifact.Kind, waveformartifact.FormatVersion, waveformartifact.AlgorithmVersion)
	if artifactErr == nil && artifact.SourceFingerprint == source.Fingerprint && source.Fingerprint != "" && artifact.Encoding == waveformartifact.Encoding && artifact.Provenance == "measured" {
		if overview, decodeErr := waveformartifact.Decode(artifact.Data); decodeErr == nil {
			respondJSON(w, WaveformResponse{TrackID: trackID, Duration: overview.Duration(), SampleRate: overview.SampleRate, Resolution: overview.Resolution, Peaks: overview.Peaks})
			return
		}
	}
	overview, decodeErr := analysis.GenerateWaveformOverviewWithOpener(r.Context(), waveformDecoders(), source.Name, source.Open, analysis.DefaultWaveformResolution)
	waveform, err := djWaveformFromOverview(overview, decodeErr, source.Name)
	if err != nil {
		if errors.Is(err, errClientWaveformRequired) {
			respondError(w, 422, "Waveform will be generated by the client for this audio format")
			return
		}
		respondError(w, 500, "Waveform generation failed")
		return
	}
	current, err := a.resolveAnalysisSource(r.Context(), trackID)
	if err != nil || current.Fingerprint != source.Fingerprint || r.Context().Err() != nil {
		respondError(w, 409, "Track source changed during waveform generation")
		return
	}
	encoded, err := waveformartifact.Encode(overview)
	if err != nil {
		respondError(w, 500, "Waveform validation failed")
		return
	}
	if err = a.db.UpsertTrackAnalysisArtifact(db.TrackAnalysisArtifact{ID: trackID + ":" + waveformartifact.AlgorithmVersion, SongID: trackID, Kind: waveformartifact.Kind, FormatVersion: waveformartifact.FormatVersion, AlgorithmVersion: waveformartifact.AlgorithmVersion, Encoding: waveformartifact.Encoding, Provenance: "measured", SourceFingerprint: source.Fingerprint, Data: encoded}); err != nil {
		logger.API("DJ waveform: artifact persistence failed for %s", trackID)
	}

	respondJSON(w, WaveformResponse{
		TrackID:    trackID,
		Duration:   waveform.Duration,
		SampleRate: waveform.SampleRate,
		Resolution: waveform.Resolution,
		Peaks:      waveform.Peaks,
	})
}

// getDJHotCues returns hot cue points for a track.
// GET /api/dj/hotcues/{id}
func (a *API) getDJHotCues(w http.ResponseWriter, r *http.Request) {
	trackID := chi.URLParam(r, "id")
	if trackID == "" {
		respondError(w, http.StatusBadRequest, "Track ID required")
		return
	}

	hotCues, err := a.db.GetDJHotCues(trackID)
	if err != nil {
		logger.API("DJ hot cues: failed to get for %s: %v", trackID, err)
		respondError(w, http.StatusInternalServerError, "Failed to get hot cues")
		return
	}

	response := HotCuesResponse{
		TrackID: trackID,
		HotCues: make([]HotCue, 0, len(hotCues)),
	}

	for _, hc := range hotCues {
		response.HotCues = append(response.HotCues, HotCue{
			Slot:              hc.Slot,
			Position:          hc.Position,
			Label:             hc.Label,
			Color:             hc.Color,
			Origin:            hc.Origin,
			GeneratorVersion:  hc.GeneratorVersion,
			Confidence:        hc.Confidence,
			Kind:              hc.Kind,
			Locked:            hc.Locked,
			Rationale:         hc.Rationale,
			SourceFingerprint: hc.SourceFingerprint,
			DownbeatAligned:   hc.DownbeatAligned,
			UpdatedAt:         hc.UpdatedAt,
		})
	}

	respondJSON(w, response)
}

// saveDJHotCues saves hot cue points for a track.
// PUT /api/dj/hotcues/{id}
func (a *API) saveDJHotCues(w http.ResponseWriter, r *http.Request) {
	trackID := chi.URLParam(r, "id")
	if trackID == "" {
		respondError(w, http.StatusBadRequest, "Track ID required")
		return
	}

	var req HotCuesResponse
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, "Invalid request body")
		return
	}

	// Convert to database format
	dbHotCues := make([]db.DJHotCue, 0, len(req.HotCues))
	seenSlots := make(map[int]struct{}, len(req.HotCues))
	for _, hc := range req.HotCues {
		if hc.Slot < 1 || hc.Slot > 8 {
			respondError(w, http.StatusBadRequest, "Hot cue slots must be between 1 and 8")
			return
		}
		if _, exists := seenSlots[hc.Slot]; exists {
			respondError(w, http.StatusBadRequest, "Hot cue slots must be unique")
			return
		}
		seenSlots[hc.Slot] = struct{}{}
		if hc.Origin != "" && hc.Origin != "user" && hc.Origin != "analysis" {
			respondError(w, http.StatusBadRequest, "Hot cue origin must be user or analysis")
			return
		}
		if hc.Origin == "" {
			hc.Origin = "user"
		}
		if hc.Origin == "analysis" && hc.DownbeatAligned && hc.Rationale != "qualified-measured-downbeat" && hc.Rationale != "qualified-manual-downbeat" {
			respondError(w, http.StatusBadRequest, "Analysis cue downbeat alignment requires measured or manual provenance")
			return
		}
		dbHotCues = append(dbHotCues, db.DJHotCue{
			Slot:              hc.Slot,
			Position:          hc.Position,
			Label:             hc.Label,
			Color:             hc.Color,
			Origin:            hc.Origin,
			GeneratorVersion:  hc.GeneratorVersion,
			Confidence:        hc.Confidence,
			Kind:              hc.Kind,
			Locked:            hc.Locked,
			Rationale:         hc.Rationale,
			SourceFingerprint: hc.SourceFingerprint,
			DownbeatAligned:   hc.DownbeatAligned,
			UpdatedAt:         hc.UpdatedAt,
		})
	}

	if err := a.db.SaveDJHotCues(trackID, dbHotCues); err != nil {
		logger.API("DJ hot cues: failed to save for %s: %v", trackID, err)
		respondError(w, http.StatusInternalServerError, "Failed to save hot cues")
		return
	}

	respondJSON(w, map[string]bool{"success": true})
}

// waveformDecoders is the shared analysis decoder registry. Server-side
// waveform support is therefore exactly the backend codec capability matrix,
// not a second hand-maintained switch that can drift from it.
var waveformDecoders = sync.OnceValue(analysis.NewDefaultDecoderRegistry)

// generateWaveform generates peak data from an audio file.
// Returns normalized peak values (0-1) at specified resolution.
//
// Decoding, downmixing, and chunk bounds are owned by internal/analysis, so
// the waveform overview, tempo, and key all read one PCM implementation.
// Formats with no backend decoder return errClientWaveformRequired and are
// deferred to Web Audio in the renderer.
func generateWaveform(filePath string) (*db.DJWaveform, error) {
	return generateWaveformWith(context.Background(), waveformDecoders(), filePath)
}

func generateWaveformWith(ctx context.Context, registry *analysis.DecoderRegistry, filePath string) (*db.DJWaveform, error) {
	overview, err := analysis.GenerateWaveformOverview(ctx, registry, filePath, analysis.DefaultWaveformResolution)
	return djWaveformFromOverview(overview, err, filePath)
}

func generateWaveformSource(ctx context.Context, source analysis.ResolvedSource) (*db.DJWaveform, error) {
	overview, err := analysis.GenerateWaveformOverviewWithOpener(ctx, waveformDecoders(), source.Name, source.Open, analysis.DefaultWaveformResolution)
	return djWaveformFromOverview(overview, err, source.Name)
}

func djWaveformFromOverview(overview analysis.WaveformOverview, err error, name string) (*db.DJWaveform, error) {
	if err != nil {
		if errors.Is(err, analysis.ErrUnsupportedCodec) {
			// Report the format that was refused so the fallback is auditable.
			extension := strings.TrimPrefix(strings.ToLower(filepath.Ext(name)), ".")
			if extension == "" {
				extension = "unknown"
			}
			return nil, fmt.Errorf("%w: %s format", errClientWaveformRequired, extension)
		}
		return nil, err
	}
	return &db.DJWaveform{
		Duration:   overview.Duration(),
		SampleRate: overview.SampleRate,
		Resolution: overview.Resolution,
		Peaks:      overview.Peaks,
	}, nil
}
