// Package api provides DJ waveform generation and analysis endpoints.
//
// This file implements:
//   - Waveform peak generation from audio files
//   - DJ analysis caching (waveform data, hot cues)
//   - Waveform data serving via REST API
//
// Waveforms are generated lazily on first request and cached in SQLite.
package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"path/filepath"
	"strings"
	"sync"

	"github.com/ajbergh/viib-mediahub/internal/analysis"
	"github.com/ajbergh/viib-mediahub/internal/db"
	"github.com/ajbergh/viib-mediahub/internal/logger"
	"github.com/go-chi/chi/v5"
)

// errClientWaveformRequired marks formats which the browser can decode but the
// server intentionally does not decode. Callers should fall back to Web Audio.
var errClientWaveformRequired = errors.New("client-side waveform generation required")

// WaveformResponse contains the waveform peak data for a track.
type WaveformResponse struct {
	TrackID    string    `json:"trackId"`
	Duration   float64   `json:"duration"`   // Total duration in seconds
	SampleRate int       `json:"sampleRate"` // Source sample rate
	Resolution int       `json:"resolution"` // Samples per peak (e.g., 256)
	Peaks      []float64 `json:"peaks"`      // Normalized peak values (0-1)
}

// HotCue represents a saved position in a track.
type HotCue struct {
	Slot     int     `json:"slot"`     // 1-8
	Position float64 `json:"position"` // Position in seconds
	Label    string  `json:"label,omitempty"`
	Color    string  `json:"color"` // Hex color code
}

// HotCuesResponse contains hot cue data for a track.
type HotCuesResponse struct {
	TrackID string   `json:"trackId"`
	HotCues []HotCue `json:"hotCues"`
}

// getDJWaveform generates or returns cached waveform data for a track.
// GET /api/dj/waveform/{id}
func (a *API) getDJWaveform(w http.ResponseWriter, r *http.Request) {
	trackID := chi.URLParam(r, "id")
	if trackID == "" {
		respondError(w, http.StatusBadRequest, "Track ID required")
		return
	}

	// Check cache first
	cached, err := a.db.GetDJWaveform(trackID)
	if err == nil && cached != nil {
		// Return cached waveform
		respondJSON(w, WaveformResponse{
			TrackID:    trackID,
			Duration:   cached.Duration,
			SampleRate: cached.SampleRate,
			Resolution: cached.Resolution,
			Peaks:      cached.Peaks,
		})
		return
	}

	// Get song from database to find file path
	song, err := a.db.GetSongByID(trackID)
	if err != nil {
		logger.API("DJ waveform: song not found: %s - %v", trackID, err)
		respondError(w, http.StatusNotFound, "Track not found")
		return
	}

	// Generate waveform from audio file
	waveform, err := generateWaveform(song.FilePath)
	if err != nil {
		if errors.Is(err, errClientWaveformRequired) {
			logger.API("DJ waveform: using client generation for %s: %v", trackID, err)
			respondError(w, http.StatusUnprocessableEntity, "Waveform will be generated by the client for this audio format")
			return
		}
		logger.API("DJ waveform: generation failed for %s: %v", trackID, err)
		respondError(w, http.StatusInternalServerError, fmt.Sprintf("Waveform generation failed: %v", err))
		return
	}

	// Cache the waveform
	if err := a.db.SaveDJWaveform(trackID, waveform); err != nil {
		logger.API("DJ waveform: failed to cache for %s: %v", trackID, err)
		// Continue anyway, just don't cache
	}

	respondJSON(w, WaveformResponse{
		TrackID:    trackID,
		Duration:   waveform.Duration,
		SampleRate: waveform.SampleRate,
		Resolution: waveform.Resolution,
		Peaks:      waveform.Peaks,
	})
}

// getDJHotCues returns hot cue points for a track.
// GET /api/dj/hotcues/{id}
func (a *API) getDJHotCues(w http.ResponseWriter, r *http.Request) {
	trackID := chi.URLParam(r, "id")
	if trackID == "" {
		respondError(w, http.StatusBadRequest, "Track ID required")
		return
	}

	hotCues, err := a.db.GetDJHotCues(trackID)
	if err != nil {
		logger.API("DJ hot cues: failed to get for %s: %v", trackID, err)
		respondError(w, http.StatusInternalServerError, "Failed to get hot cues")
		return
	}

	response := HotCuesResponse{
		TrackID: trackID,
		HotCues: make([]HotCue, 0, len(hotCues)),
	}

	for _, hc := range hotCues {
		response.HotCues = append(response.HotCues, HotCue{
			Slot:     hc.Slot,
			Position: hc.Position,
			Label:    hc.Label,
			Color:    hc.Color,
		})
	}

	respondJSON(w, response)
}

// saveDJHotCues saves hot cue points for a track.
// PUT /api/dj/hotcues/{id}
func (a *API) saveDJHotCues(w http.ResponseWriter, r *http.Request) {
	trackID := chi.URLParam(r, "id")
	if trackID == "" {
		respondError(w, http.StatusBadRequest, "Track ID required")
		return
	}

	var req HotCuesResponse
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, "Invalid request body")
		return
	}

	// Convert to database format
	dbHotCues := make([]db.DJHotCue, 0, len(req.HotCues))
	for _, hc := range req.HotCues {
		dbHotCues = append(dbHotCues, db.DJHotCue{
			Slot:     hc.Slot,
			Position: hc.Position,
			Label:    hc.Label,
			Color:    hc.Color,
		})
	}

	if err := a.db.SaveDJHotCues(trackID, dbHotCues); err != nil {
		logger.API("DJ hot cues: failed to save for %s: %v", trackID, err)
		respondError(w, http.StatusInternalServerError, "Failed to save hot cues")
		return
	}

	respondJSON(w, map[string]bool{"success": true})
}

// waveformDecoders is the shared analysis decoder registry. Server-side
// waveform support is therefore exactly the backend codec capability matrix,
// not a second hand-maintained switch that can drift from it.
var waveformDecoders = sync.OnceValue(analysis.NewDefaultDecoderRegistry)

// generateWaveform generates peak data from an audio file.
// Returns normalized peak values (0-1) at specified resolution.
//
// Decoding, downmixing, and chunk bounds are owned by internal/analysis, so
// the waveform overview, tempo, and key all read one PCM implementation.
// Formats with no backend decoder return errClientWaveformRequired and are
// deferred to Web Audio in the renderer.
func generateWaveform(filePath string) (*db.DJWaveform, error) {
	return generateWaveformWith(context.Background(), waveformDecoders(), filePath)
}

func generateWaveformWith(ctx context.Context, registry *analysis.DecoderRegistry, filePath string) (*db.DJWaveform, error) {
	overview, err := analysis.GenerateWaveformOverview(ctx, registry, filePath, analysis.DefaultWaveformResolution)
	if err != nil {
		if errors.Is(err, analysis.ErrUnsupportedCodec) {
			// Report the format that was refused so the fallback is auditable.
			extension := strings.TrimPrefix(strings.ToLower(filepath.Ext(filePath)), ".")
			if extension == "" {
				extension = "unknown"
			}
			return nil, fmt.Errorf("%w: %s format", errClientWaveformRequired, extension)
		}
		return nil, err
	}
	return &db.DJWaveform{
		Duration:   overview.Duration(),
		SampleRate: overview.SampleRate,
		Resolution: overview.Resolution,
		Peaks:      overview.Peaks,
	}, nil
}
