/**
 * API Client for ViiB MediaHub Backend
 * 
 * This module provides a typed interface for communicating with the Go backend.
 * All API calls go through this module to ensure consistent error handling and typing.
 * 
 * Architecture:
 * - Development: Vite dev server proxies /api requests to Go backend (port 8080)
 * - Production: Backend serves both the built frontend and API from same origin
 * - All responses are JSON with consistent error format
 * - TypeScript interfaces match backend Go structs
 * 
 * Features:
 * - Library management (songs, playlists, folders)
 * - File scanning and metadata extraction
 * - Spotify OAuth credential storage
 * - Spotify download queue management
 * - Real-time download progress via SSE (handled by DownloadManager component)
 */

const API_BASE = '/api';

/**
 * Standard error response from backend
 */
interface ApiError {
  error: string;
}

/**
 * Handles HTTP responses and errors consistently.
 * Throws on non-OK status codes with error message from backend.
 * 
 * @param response - Fetch API Response object
 * @returns Parsed JSON response
 * @throws Error with backend error message or HTTP status
 */
async function handleResponse<T>(response: Response): Promise<T> {
  if (!response.ok) {
    const error: ApiError = await response.json().catch(() => ({ error: 'Unknown error' }));
    throw new Error(error.error || `HTTP ${response.status}`);
  }
  return response.json();
}

// Song types matching backend
export interface ApiSong {
  id: string;
  title: string;
  artist: string;
  album: string;
  albumArtist?: string;
  trackNumber?: number;
  discNumber?: number;
  genre?: string[];
  year?: number;
  duration: number;
  filePath: string; // This will be the API URL like /api/audio/{id}
  coverPath?: string; // This will be /api/cover/{id}
  addedAt: number;
  playCount?: number;
  lastPlayed?: number;
  skipCount?: number;
}

export interface ApiPlaylist {
  id: string;
  name: string;
  songIds: string[];
  coverPath?: string;
  createdAt: number;
}

export interface ScanFolder {
  id: string;
  path: string;
  addedAt: number;
  lastScan?: number;
  songCount: number;
}

export interface FolderEntry {
  name: string;
  path: string;
  isDir: boolean;
}

export interface BrowseResult {
  currentPath: string;
  entries: FolderEntry[];
}

export interface ScanStatus {
  scanning: boolean;
  progress: string;
}

/**
 * Represents a Spotify download in the queue.
 * Matches the SpotifyDownload struct in backend/internal/db/db.go.
 * 
 * Download Lifecycle:
 * 1. queued - Added to queue, waiting to be processed
 * 2. downloading - Currently being downloaded from Spotify
 * 3. completed - Successfully downloaded to disk
 * 4. failed - Download failed (see errorMessage)
 * 
 * Progress updates are received via SSE (Server-Sent Events) from
 * the /api/spotify/downloads/events endpoint.
 */
export interface ApiSpotifyDownload {
  id: string;                    // UUID generated by backend
  spotifyId: string;             // Spotify track ID (e.g., "3n3Ppam7vgaVa1iaRUc9Lp")
  type: 'track' | 'album' | 'playlist'; // Download type
  title: string;                 // Track/album/playlist title
  artist: string;                // Primary artist
  album: string;                 // Album name
  status: 'queued' | 'downloading' | 'completed' | 'failed'; // Current status
  progress: number;              // 0-100 percentage
  errorMessage?: string;         // Error details if status is 'failed'
  filePath?: string;             // Full path to downloaded file (if completed)
  addedAt: number;               // Unix timestamp when queued
  startedAt?: number;            // Unix timestamp when download started
  completedAt?: number;          // Unix timestamp when completed
  artworkUrl?: string;           // Album/playlist artwork URL from Spotify
}

// API Functions

export const api = {
  // Songs
  async getSongs(): Promise<ApiSong[]> {
    const response = await fetch(`${API_BASE}/songs`);
    return handleResponse(response);
  },

  async clearSongs(): Promise<void> {
    const response = await fetch(`${API_BASE}/songs`, { method: 'DELETE' });
    await handleResponse(response);
  },

  async recordPlay(songId: string): Promise<void> {
    const response = await fetch(`${API_BASE}/songs/${songId}/play`, { method: 'POST' });
    await handleResponse(response);
  },

  // Playlists
  async getPlaylists(): Promise<ApiPlaylist[]> {
    const response = await fetch(`${API_BASE}/playlists`);
    return handleResponse(response);
  },

  async createPlaylist(name: string, songIds: string[] = []): Promise<ApiPlaylist> {
    const response = await fetch(`${API_BASE}/playlists`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name, songIds }),
    });
    return handleResponse(response);
  },

  async updatePlaylist(id: string, data: Partial<ApiPlaylist>): Promise<ApiPlaylist> {
    const response = await fetch(`${API_BASE}/playlists/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    return handleResponse(response);
  },

  async deletePlaylist(id: string): Promise<void> {
    const response = await fetch(`${API_BASE}/playlists/${id}`, { method: 'DELETE' });
    await handleResponse(response);
  },

  // Folders
  async getFolders(): Promise<ScanFolder[]> {
    const response = await fetch(`${API_BASE}/folders`);
    return handleResponse(response);
  },

  async addFolder(path: string): Promise<ScanFolder> {
    const response = await fetch(`${API_BASE}/folders`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ path }),
    });
    return handleResponse(response);
  },

  async removeFolder(id: string): Promise<void> {
    const response = await fetch(`${API_BASE}/folders/${id}`, { method: 'DELETE' });
    await handleResponse(response);
  },

  // Scanning
  async startScan(): Promise<void> {
    const response = await fetch(`${API_BASE}/scan`, { method: 'POST' });
    await handleResponse(response);
  },

  async getScanStatus(): Promise<ScanStatus> {
    const response = await fetch(`${API_BASE}/scan/status`);
    return handleResponse(response);
  },

  // Browse folders
  async browseFolder(path?: string): Promise<BrowseResult> {
    const response = await fetch(`${API_BASE}/browse`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ path: path || '' }),
    });
    return handleResponse(response);
  },

  // Health check
  async healthCheck(): Promise<{ status: string; version: string }> {
    const response = await fetch(`${API_BASE}/health`);
    return handleResponse(response);
  },

  // Helper to get audio URL
  getAudioUrl(songId: string): string {
    return `${API_BASE}/audio/${songId}`;
  },

  // Helper to get cover URL
  getCoverUrl(songId: string): string {
    return `${API_BASE}/cover/${songId}`;
  },

  // Spotify Credentials
  
  /**
   * Saves Spotify OAuth credentials to backend database.
   * Credentials are stored in the spotify_credentials setting as JSON.
   * The access token is used for both Web API calls and librespot downloads.
   * 
   * @param creds - OAuth credentials from Spotify authorization flow
   * @returns Promise resolving to success response
   */
  async saveSpotifyCredentials(creds: { clientId: string; clientSecret: string; accessToken: string; refreshToken: string; expiry: number }) {
    const response = await fetch(`${API_BASE}/spotify/credentials`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(creds),
    });
    return handleResponse(response);
  },

  /**
   * Retrieves stored Spotify OAuth credentials from backend.
   * Used for checking if user is authenticated and for token refresh.
   * 
   * @returns Promise resolving to credentials or empty object if not set
   */
  async getSpotifyCredentials() {
    const response = await fetch(`${API_BASE}/spotify/credentials`);
    return handleResponse<{ clientId: string; clientSecret: string; accessToken: string; refreshToken: string; expiry: number }>(response);
  },

  // Spotify Downloads
  
  /**
   * Queues a single track for download from Spotify.
   * Requires Spotify Premium account and valid OAuth authentication.
   * Track is downloaded as OGG Vorbis format using librespot-go.
   * 
   * Backend Process:
   * 1. Adds download to spotify_downloads table with status 'queued'
   * 2. Background worker picks up download
   * 3. Authenticates with Spotify using OAuth token
   * 4. Streams and saves to {downloadDir}/{artist}/{track}.ogg
   * 5. Updates status to 'completed' or 'failed'
   * 
   * @param spotifyId - Spotify track ID
   * @param title - Track title
   * @param artist - Primary artist name
   * @param album - Album name
   * @param duration - Track duration in seconds
   * @returns Promise with download ID and confirmation message
   */
  async downloadTrack(spotifyId: string, title: string, artist: string, album: string, duration: number) {
    const response = await fetch(`${API_BASE}/spotify/download/track`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ spotifyId, title, artist, album, duration }),
    });
    return handleResponse<{ id: string; message: string }>(response);
  },

  /**
   * Queues an entire album for download from Spotify.
   * Backend fetches all tracks from Spotify Web API and queues each individually.
   * 
   * @param spotifyId - Spotify album ID
   * @param title - Album title
   * @param artist - Primary artist name
   * @returns Promise with confirmation message
   */
  async downloadAlbum(spotifyId: string, title: string, artist: string) {
    const response = await fetch(`${API_BASE}/spotify/download/album`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ spotifyId, title, artist }),
    });
    return handleResponse<{ id: string; message: string }>(response);
  },

  /**
   * Queues an entire playlist for download from Spotify.
   * Backend fetches all tracks from Spotify Web API and queues each individually.
   * 
   * @param spotifyId - Spotify playlist ID
   * @param name - Playlist name
   * @param owner - Playlist owner name
   * @returns Promise with confirmation message
   */
  async downloadPlaylist(spotifyId: string, name: string, owner: string) {
    const response = await fetch(`${API_BASE}/spotify/download/playlist`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ spotifyId, name, owner }),
    });
    return handleResponse<{ id: string; message: string }>(response);
  },

  /**
   * Downloads content directly from a Spotify URL or URI.
   * Supports tracks, albums, and playlists.
   * 
   * Accepted formats:
   * - https://open.spotify.com/track/4iV5W9uYEdYUVa79Axb7Rh
   * - https://open.spotify.com/album/1DFixLWuPkv3KT3TnV35m3
   * - https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M
   * - spotify:track:4iV5W9uYEdYUVa79Axb7Rh
   * - spotify:album:1DFixLWuPkv3KT3TnV35m3
   * - spotify:playlist:37i9dQZF1DXcBWIGoYBM5M
   * 
   * @param url - Spotify URL or URI
   * @returns Promise with download result including type, title, and count (for albums/playlists)
   */
  async downloadFromURL(url: string) {
    const response = await fetch(`${API_BASE}/spotify/download/url`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ url }),
    });
    return handleResponse<{ 
      status: string; 
      type: string;
      title: string; 
      artist?: string;
      owner?: string;
      album?: string;
      message: string; 
      count?: number;
    }>(response);
  },

  /**
   * Retrieves all downloads from the queue.
   * Includes queued, downloading, completed, and failed downloads.
   * Use this for initial state load; real-time updates come via SSE.
   * 
   * @returns Promise with array of all downloads
   */
  async getDownloads() {
    const response = await fetch(`${API_BASE}/spotify/downloads`);
    return handleResponse<ApiSpotifyDownload[]>(response);
  },

  /**
   * Gets the current status of a specific download.
   * 
   * @param id - Download ID (UUID)
   * @returns Promise with download details
   */
  async getDownloadStatus(id: string) {
    const response = await fetch(`${API_BASE}/spotify/downloads/${id}`);
    return handleResponse<ApiSpotifyDownload>(response);
  },

  /**
   * Deletes a download from the queue.
   * Cannot delete downloads that are currently in progress.
   * Does NOT delete the downloaded file from disk (if completed).
   * 
   * @param id - Download ID (UUID)
   * @returns Promise resolving when deleted
   */
  async deleteDownload(id: string) {
    const response = await fetch(`${API_BASE}/spotify/downloads/${id}`, { method: 'DELETE' });
    await handleResponse(response);
  },

  /**
   * Retries a failed download by resetting it to queued status.
   * 
   * @param id - Download ID (UUID)
   * @returns Promise resolving when reset
   */
  async retryDownload(id: string) {
    const response = await fetch(`${API_BASE}/spotify/downloads/${id}/retry`, { method: 'POST' });
    await handleResponse(response);
  },

  /**
   * Clears all completed downloads from the queue.
   * Does NOT delete the downloaded files from disk.
   * 
   * @returns Promise with count of cleared downloads
   */
  async clearCompletedDownloads(): Promise<{ count: number }> {
    const response = await fetch(`${API_BASE}/spotify/downloads/completed`, { method: 'DELETE' });
    return handleResponse<{ status: string; count: number }>(response);
  },

  // Settings

  /**
   * Gets a setting value from the backend.
   * 
   * @param key - Setting key
   * @returns Promise with setting value (empty string if not set)
   */
  async getSetting(key: string): Promise<string> {
    const response = await fetch(`${API_BASE}/settings/${key}`);
    const data = await handleResponse<{ key: string; value: string }>(response);
    return data.value;
  },

  /**
   * Sets a setting value in the backend.
   * 
   * @param key - Setting key
   * @param value - Setting value
   * @returns Promise resolving when saved
   */
  async setSetting(key: string, value: string) {
    const response = await fetch(`${API_BASE}/settings/${key}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ value }),
    });
    await handleResponse(response);
  },
};

export default api;
