/**
 * API Client for ViiB MediaHub Backend
 * 
 * This module provides a typed interface for communicating with the Go backend.
 * All API calls go through this module to ensure consistent error handling and typing.
 * 
 * Architecture:
 * - Development: Vite dev server proxies /api requests to Go backend (port 8080)
 * - Production: Backend serves both the built frontend and API from same origin
 * - All responses are JSON with consistent error format
 * - TypeScript interfaces match backend Go structs
 * 
 * Features:
 * - Library management (songs, playlists, folders)
 * - File scanning and metadata extraction
 * - Spotify OAuth credential storage
 * - Spotify download queue management
 * - Real-time download progress via SSE (handled by DownloadManager component)
 * 
 * AI DJ Features:
 * - generateSmartPlaylist: Natural language playlist generation with multi-tier matching
 * - enrichGenresStream: SSE-based genre enrichment using Gemini AI
 * - enrichMoodStream: SSE-based mood/energy/tempo analysis using Gemini AI
 * 
 * Smart Playlist Options:
 * - blendMode: 'single' or 'mixed' for genre blending
 * - discoverMode: 'balanced', 'discover', 'favorites' for play history preferences
 * - avoidRecentlyHours: Exclude recently played songs
 * - onePerArtist: Limit to one song per artist for variety
 * - useTimeContext: Add time-of-day context to recommendations
 */

const API_BASE = '/api';

/**
 * Standard error response from backend
 */
interface ApiError {
  error: string;
}

/**
 * Handles HTTP responses and errors consistently.
 * Throws on non-OK status codes with error message from backend.
 * 
 * @param response - Fetch API Response object
 * @returns Parsed JSON response
 * @throws Error with backend error message or HTTP status
 */
async function handleResponse<T>(response: Response): Promise<T> {
  if (!response.ok) {
    const error: ApiError = await response.json().catch(() => ({ error: 'Unknown error' }));
    throw new Error(error.error || `HTTP ${response.status}`);
  }
  return response.json();
}

// Song types matching backend
export interface ApiSong {
  id: string;
  title: string;
  artist: string;
  album: string;
  albumArtist?: string;
  trackNumber?: number;
  discNumber?: number;
  genre?: string[];
  year?: number;
  duration: number;
  filePath: string; // This will be the API URL like /api/audio/{id}
  coverPath?: string; // This will be /api/cover/{id}
  addedAt: number;
  playCount?: number;
  lastPlayed?: number;
  skipCount?: number;
}

export interface ApiPlaylist {
  id: string;
  name: string;
  songIds: string[];
  coverPath?: string;
  createdAt: number;
}

export interface ScanFolder {
  id: string;
  path: string;
  addedAt: number;
  lastScan?: number;
  songCount: number;
}

/**
 * Progress update from genre enrichment SSE stream
 */
export interface EnrichmentProgress {
  status: 'started' | 'processing' | 'batch_complete' | 'complete' | 'error';
  message: string;
  totalSongs: number;
  processedSongs: number;
  currentBatch: number;
  totalBatches: number;
  error?: string;
}

export interface FolderEntry {
  name: string;
  path: string;
  isDir: boolean;
}

export interface BrowseResult {
  currentPath: string;
  entries: FolderEntry[];
}

export interface ScanStatus {
  scanning: boolean;
  progress: string;
}

export interface GenreStat {
  name: string;
  count: number;
  topArtists: string[];
  coverUrl?: string;
}

/**
 * Represents a Spotify download in the queue.
 * Matches the SpotifyDownload struct in backend/internal/db/db.go.
 * 
 * Download Lifecycle:
 * 1. queued - Added to queue, waiting to be processed
 * 2. downloading - Currently being downloaded from Spotify
 * 3. completed - Successfully downloaded to disk
 * 4. failed - Download failed (see errorMessage)
 * 
 * Progress updates are received via SSE (Server-Sent Events) from
 * the /api/spotify/downloads/events endpoint.
 */
export interface ApiSpotifyDownload {
  id: string;                    // UUID generated by backend
  spotifyId: string;             // Spotify track ID (e.g., "3n3Ppam7vgaVa1iaRUc9Lp")
  type: 'track' | 'album' | 'playlist'; // Download type
  title: string;                 // Track/album/playlist title
  artist: string;                // Primary artist
  album: string;                 // Album name
  status: 'queued' | 'downloading' | 'completed' | 'failed'; // Current status
  progress: number;              // 0-100 percentage
  errorMessage?: string;         // Error details if status is 'failed'
  filePath?: string;             // Full path to downloaded file (if completed)
  addedAt: number;               // Unix timestamp when queued
  startedAt?: number;            // Unix timestamp when download started
  completedAt?: number;          // Unix timestamp when completed
  artworkUrl?: string;           // Album/playlist artwork URL from Spotify
}

// API Functions

export const api = {
  // Songs
  async getSongs(): Promise<ApiSong[]> {
    const response = await fetch(`${API_BASE}/songs`);
    return handleResponse(response);
  },

  async getGenres(): Promise<GenreStat[]> {
    const response = await fetch(`${API_BASE}/genres`);
    return handleResponse(response);
  },

  async clearSongs(): Promise<void> {
    const response = await fetch(`${API_BASE}/songs`, { method: 'DELETE' });
    await handleResponse(response);
  },

  async recordPlay(songId: string): Promise<void> {
    const response = await fetch(`${API_BASE}/songs/${songId}/play`, { method: 'POST' });
    await handleResponse(response);
  },

  // Playlists
  async getPlaylists(): Promise<ApiPlaylist[]> {
    const response = await fetch(`${API_BASE}/playlists`);
    return handleResponse(response);
  },

  async createPlaylist(name: string, songIds: string[] = []): Promise<ApiPlaylist> {
    const response = await fetch(`${API_BASE}/playlists`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name, songIds }),
    });
    return handleResponse(response);
  },

  async updatePlaylist(id: string, data: Partial<ApiPlaylist>): Promise<ApiPlaylist> {
    const response = await fetch(`${API_BASE}/playlists/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    return handleResponse(response);
  },

  async deletePlaylist(id: string): Promise<void> {
    const response = await fetch(`${API_BASE}/playlists/${id}`, { method: 'DELETE' });
    await handleResponse(response);
  },

  // Folders
  async getFolders(): Promise<ScanFolder[]> {
    const response = await fetch(`${API_BASE}/folders`);
    return handleResponse(response);
  },

  async addFolder(path: string): Promise<ScanFolder> {
    const response = await fetch(`${API_BASE}/folders`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ path }),
    });
    return handleResponse(response);
  },

  async removeFolder(id: string): Promise<void> {
    const response = await fetch(`${API_BASE}/folders/${id}`, { method: 'DELETE' });
    await handleResponse(response);
  },

  // Scanning
  async startScan(): Promise<void> {
    const response = await fetch(`${API_BASE}/scan`, { method: 'POST' });
    await handleResponse(response);
  },

  async getScanStatus(): Promise<ScanStatus> {
    const response = await fetch(`${API_BASE}/scan/status`);
    return handleResponse(response);
  },

  // Browse folders
  async browseFolder(path?: string): Promise<BrowseResult> {
    const response = await fetch(`${API_BASE}/browse`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ path: path || '' }),
    });
    return handleResponse(response);
  },

  // Health check
  async healthCheck(): Promise<{ status: string; version: string }> {
    const response = await fetch(`${API_BASE}/health`);
    return handleResponse(response);
  },

  // Helper to get audio URL
  getAudioUrl(songId: string): string {
    return `${API_BASE}/audio/${songId}`;
  },

  // Helper to get cover URL
  getCoverUrl(songId: string): string {
    return `${API_BASE}/cover/${songId}`;
  },

  // Helper to get Spotify stream URL
  // Used for direct streaming of Spotify tracks without downloading
  // Quality parameter: 'high' (320kbps), 'medium' (160kbps), 'low' (96kbps)
  getSpotifyStreamUrl(spotifyId: string, quality?: 'high' | 'medium' | 'low'): string {
    const qualityParam = quality ? `?quality=${quality}` : '';
    return `${API_BASE}/spotify/stream/${spotifyId}${qualityParam}`;
  },

  // Spotify Credentials

  /**
   * Saves Spotify OAuth credentials to backend database.
   * Credentials are stored in the spotify_credentials setting as JSON.
   * The access token is used for both Web API calls and librespot downloads.
   * 
   * @param creds - OAuth credentials from Spotify authorization flow
   * @returns Promise resolving to success response
   */
  async saveSpotifyCredentials(creds: { clientId: string; clientSecret: string; accessToken: string; refreshToken: string; expiry: number }) {
    const response = await fetch(`${API_BASE}/spotify/credentials`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(creds),
    });
    return handleResponse(response);
  },

  /**
   * Retrieves stored Spotify OAuth credentials from backend.
   * Used for checking if user is authenticated and for token refresh.
   * 
   * @returns Promise resolving to credentials or empty object if not set
   */
  async getSpotifyCredentials() {
    const response = await fetch(`${API_BASE}/spotify/credentials`);
    return handleResponse<{ clientId: string; clientSecret: string; accessToken: string; refreshToken: string; expiry: number }>(response);
  },

  // Spotify Downloads

  /**
   * Queues a single track for download from Spotify.
   * Requires Spotify Premium account and valid OAuth authentication.
   * Track is downloaded as OGG Vorbis format using librespot-go.
   * 
   * Backend Process:
   * 1. Adds download to spotify_downloads table with status 'queued'
   * 2. Background worker picks up download
   * 3. Authenticates with Spotify using OAuth token
   * 4. Streams and saves to {downloadDir}/{artist}/{track}.ogg
   * 5. Updates status to 'completed' or 'failed'
   * 
   * @param spotifyId - Spotify track ID
   * @param title - Track title
   * @param artist - Primary artist name
   * @param album - Album name
   * @param duration - Track duration in seconds
   * @returns Promise with download ID and confirmation message
   */
  async downloadTrack(spotifyId: string, title: string, artist: string, album: string, duration: number) {
    const response = await fetch(`${API_BASE}/spotify/download/track`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ spotifyId, title, artist, album, duration }),
    });
    return handleResponse<{ id: string; message: string }>(response);
  },

  /**
   * Queues an entire album for download from Spotify.
   * Backend fetches all tracks from Spotify Web API and queues each individually.
   * 
   * @param spotifyId - Spotify album ID
   * @param title - Album title
   * @param artist - Primary artist name
   * @returns Promise with confirmation message
   */
  async downloadAlbum(spotifyId: string, title: string, artist: string) {
    const response = await fetch(`${API_BASE}/spotify/download/album`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ spotifyId, title, artist }),
    });
    return handleResponse<{ id: string; message: string }>(response);
  },

  /**
   * Queues an entire playlist for download from Spotify.
   * Backend fetches all tracks from Spotify Web API and queues each individually.
   * 
   * @param spotifyId - Spotify playlist ID
   * @param name - Playlist name
   * @param owner - Playlist owner name
   * @returns Promise with confirmation message
   */
  async downloadPlaylist(spotifyId: string, name: string, owner: string) {
    const response = await fetch(`${API_BASE}/spotify/download/playlist`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ spotifyId, name, owner }),
    });
    return handleResponse<{ id: string; message: string }>(response);
  },

  /**
   * Downloads content directly from a Spotify URL or URI.
   * Supports tracks, albums, and playlists.
   * 
   * Accepted formats:
   * - https://open.spotify.com/track/4iV5W9uYEdYUVa79Axb7Rh
   * - https://open.spotify.com/album/1DFixLWuPkv3KT3TnV35m3
   * - https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M
   * - spotify:track:4iV5W9uYEdYUVa79Axb7Rh
   * - spotify:album:1DFixLWuPkv3KT3TnV35m3
   * - spotify:playlist:37i9dQZF1DXcBWIGoYBM5M
   * 
   * @param url - Spotify URL or URI
   * @returns Promise with download result including type, title, and count (for albums/playlists)
   */
  async downloadFromURL(url: string) {
    const response = await fetch(`${API_BASE}/spotify/download/url`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ url }),
    });
    return handleResponse<{
      status: string;
      type: string;
      title: string;
      artist?: string;
      owner?: string;
      album?: string;
      message: string;
      count?: number;
    }>(response);
  },

  /**
   * Retrieves all downloads from the queue.
   * Includes queued, downloading, completed, and failed downloads.
   * Use this for initial state load; real-time updates come via SSE.
   * 
   * @returns Promise with array of all downloads
   */
  async getDownloads() {
    const response = await fetch(`${API_BASE}/spotify/downloads`);
    return handleResponse<ApiSpotifyDownload[]>(response);
  },

  /**
   * Gets the current status of a specific download.
   * 
   * @param id - Download ID (UUID)
   * @returns Promise with download details
   */
  async getDownloadStatus(id: string) {
    const response = await fetch(`${API_BASE}/spotify/downloads/${id}`);
    return handleResponse<ApiSpotifyDownload>(response);
  },

  /**
   * Deletes a download from the queue.
   * Cannot delete downloads that are currently in progress.
   * Does NOT delete the downloaded file from disk (if completed).
   * 
   * @param id - Download ID (UUID)
   * @returns Promise resolving when deleted
   */
  async deleteDownload(id: string) {
    const response = await fetch(`${API_BASE}/spotify/downloads/${id}`, { method: 'DELETE' });
    await handleResponse(response);
  },

  /**
   * Retries a failed download by resetting it to queued status.
   * 
   * @param id - Download ID (UUID)
   * @returns Promise resolving when reset
   */
  async retryDownload(id: string) {
    const response = await fetch(`${API_BASE}/spotify/downloads/${id}/retry`, { method: 'POST' });
    await handleResponse(response);
  },

  /**
   * Clears all completed downloads from the queue.
   * Does NOT delete the downloaded files from disk.
   * 
   * @returns Promise with count of cleared downloads
   */
  async clearCompletedDownloads(): Promise<{ count: number }> {
    const response = await fetch(`${API_BASE}/spotify/downloads/completed`, { method: 'DELETE' });
    return handleResponse<{ status: string; count: number }>(response);
  },

  // Settings

  /**
   * Gets a setting value from the backend.
   * 
   * @param key - Setting key
   * @returns Promise with setting value (empty string if not set)
   */
  async getSetting(key: string): Promise<string> {
    const response = await fetch(`${API_BASE}/settings/${key}`);
    const data = await handleResponse<{ key: string; value: string }>(response);
    return data.value;
  },

  /**
   * Sets a setting value in the backend.
   * 
   * @param key - Setting key
   * @param value - Setting value
   * @returns Promise resolving when saved
   */
  async setSetting(key: string, value: string) {
    const response = await fetch(`${API_BASE}/settings/${key}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ value }),
    });
    await handleResponse(response);
  },

  // Album Metadata Cache

  /**
   * Gets all cached album metadata from the backend.
   * Used for fast startup to avoid re-fetching from Spotify.
   * 
   * @returns Promise with all cached album metadata
   */
  async getAllAlbumMetadata(): Promise<ApiAlbumMetadata[]> {
    const response = await fetch(`${API_BASE}/albums/metadata`);
    return handleResponse<ApiAlbumMetadata[]>(response);
  },

  /**
   * Gets cached metadata for a specific album.
   * 
   * @param albumKey - Album key in "albumName::artistName" format
   * @returns Promise with album metadata or null if not found
   */
  async getAlbumMetadata(albumKey: string): Promise<ApiAlbumMetadata | null> {
    try {
      const response = await fetch(`${API_BASE}/albums/metadata/${encodeURIComponent(albumKey)}`);
      if (response.status === 404) return null;
      return handleResponse<ApiAlbumMetadata>(response);
    } catch {
      return null;
    }
  },

  /**
   * Saves album metadata to the backend cache.
   * Also marks whether Spotify was checked and if data was found.
   * 
   * @param metadata - Album metadata to save
   */
  async saveAlbumMetadata(metadata: ApiAlbumMetadata): Promise<void> {
    const response = await fetch(`${API_BASE}/albums/metadata`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(metadata),
    });
    await handleResponse(response);
  },

  /**
   * Downloads album artwork to the album's folder as cover.jpg.
   * Uses the first song in the album to determine the folder path.
   * 
   * @param albumKey - Album key in "albumName::artistName" format
   * @param imageUrl - URL of the image to download
   * @returns Promise with the local cover path
   */
  async downloadAlbumCover(albumKey: string, imageUrl: string): Promise<{ coverPath: string }> {
    const response = await fetch(`${API_BASE}/albums/metadata/download-cover`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ albumKey, imageUrl }),
    });
    return handleResponse<{ status: string; coverPath: string }>(response);
  },

  /**
   * Resets the Spotify check status for an album to force re-fetch.
   * Call this when user wants to manually refresh metadata from Spotify.
   * 
   * @param albumKey - Album key in "albumName::artistName" format
   */
  async resetAlbumMetadata(albumKey: string): Promise<void> {
    const response = await fetch(`${API_BASE}/albums/metadata/${encodeURIComponent(albumKey)}`, {
      method: 'DELETE',
    });
    await handleResponse(response);
  },

  /**
   * Gets metadata for multiple albums in a single request.
   * More efficient than calling getAlbumMetadata for each album.
   * 
   * @param albumKeys - Array of album keys in "albumName::artistName" format
   * @returns Promise with array of album metadata
   */
  async batchGetAlbumMetadata(albumKeys: string[]): Promise<ApiAlbumMetadata[]> {
    if (albumKeys.length === 0) return [];
    const response = await fetch(`${API_BASE}/albums/metadata/batch`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ albumKeys }),
    });
    return handleResponse<ApiAlbumMetadata[]>(response);
  },

  /**
   * Gets albums that haven't been checked on Spotify yet.
   * Used for background metadata enrichment.
   * 
   * @returns Promise with albums needing Spotify check
   */
  async getUncheckedAlbumMetadata(): Promise<ApiAlbumMetadata[]> {
    const response = await fetch(`${API_BASE}/albums/metadata/unchecked`);
    return handleResponse<ApiAlbumMetadata[]>(response);
  },

  /**
   * Gets albums that were checked but not found, and are past expiration.
   * These should be re-checked as Spotify catalog changes over time.
   * 
   * @returns Promise with expired album metadata needing re-check
   */
  async getExpiredAlbumMetadata(): Promise<ApiAlbumMetadata[]> {
    const response = await fetch(`${API_BASE}/albums/metadata/expired`);
    return handleResponse<ApiAlbumMetadata[]>(response);
  },

  // Artist metadata endpoints

  /**
   * Gets all cached artist metadata from the backend.
   * 
   * @returns Promise with all cached artist metadata
   */
  async getAllArtistMetadata(): Promise<ApiArtistMetadata[]> {
    const response = await fetch(`${API_BASE}/artists/metadata`);
    return handleResponse<ApiArtistMetadata[]>(response);
  },

  /**
   * Gets cached metadata for a specific artist.
   * 
   * @param artistName - Artist name
   * @returns Promise with artist metadata or null if not found
   */
  async getArtistMetadata(artistName: string): Promise<ApiArtistMetadata | null> {
    try {
      const response = await fetch(`${API_BASE}/artists/metadata/${encodeURIComponent(artistName)}`);
      if (response.status === 404) return null;
      return handleResponse<ApiArtistMetadata>(response);
    } catch {
      return null;
    }
  },

  /**
   * Saves artist metadata to the backend cache.
   * 
   * @param metadata - Artist metadata to save
   */
  async saveArtistMetadata(metadata: ApiArtistMetadata): Promise<void> {
    const response = await fetch(`${API_BASE}/artists/metadata`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(metadata),
    });
    await handleResponse(response);
  },

  /**
   * Downloads artist image to local cache.
   * 
   * @param artistName - Artist name
   * @param imageUrl - URL of the image to download
   * @returns Promise with the local image path
   */
  async downloadArtistImage(artistName: string, imageUrl: string): Promise<{ imagePath: string }> {
    const response = await fetch(`${API_BASE}/artists/metadata/download-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ artistName, imageUrl }),
    });
    return handleResponse<{ status: string; imagePath: string }>(response);
  },

  /**
   * Resets the Spotify check status for an artist to force re-fetch.
   * 
   * @param artistName - Artist name
   */
  async resetArtistMetadata(artistName: string): Promise<void> {
    const response = await fetch(`${API_BASE}/artists/metadata/${encodeURIComponent(artistName)}`, {
      method: 'DELETE',
    });
    await handleResponse(response);
  },

  /**
   * Gets artists that haven't been checked on Spotify yet.
   * 
   * @returns Promise with artists needing Spotify check
   */
  async getUncheckedArtistMetadata(): Promise<ApiArtistMetadata[]> {
    const response = await fetch(`${API_BASE}/artists/metadata/unchecked`);
    return handleResponse<ApiArtistMetadata[]>(response);
  },
  /**
   * Triggers the Gemini genre enrichment process.
   * @param apiKey - Optional Gemini API key. If not provided, backend will use stored key.
   * @param force - If true, re-checks all songs. If false, only checks songs with missing genres.
   * @param offset - Pagination offset for processing large libraries in batches.
   * @returns Result of the enrichment process.
   */
  async enrichGenres(apiKey?: string, force: boolean = false, offset: number = 0): Promise<{ status: string; message: string; count: number }> {
    const response = await fetch(`${API_BASE}/library/enrich-genres`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ apiKey, force, offset }),
    });
    return handleResponse(response);
  },

  /**
   * Streams genre enrichment progress via SSE.
   * @param force - If true, re-checks all songs.
   * @param onProgress - Callback for progress updates.
   * @returns EventSource instance for cleanup.
   */
  enrichGenresStream(
    force: boolean = false,
    onProgress: (progress: EnrichmentProgress) => void
  ): EventSource {
    const url = `${API_BASE}/library/enrich-genres/stream?force=${force}`;
    const eventSource = new EventSource(url);

    eventSource.onmessage = (event) => {
      try {
        const progress = JSON.parse(event.data) as EnrichmentProgress;
        onProgress(progress);
        
        // Auto-close on completion or error
        if (progress.status === 'complete' || progress.status === 'error') {
          eventSource.close();
        }
      } catch (e) {
        console.error('Failed to parse enrichment progress:', e);
      }
    };

    eventSource.onerror = () => {
      onProgress({
        status: 'error',
        message: 'Connection lost',
        error: 'SSE connection failed',
        totalSongs: 0,
        processedSongs: 0,
        currentBatch: 0,
        totalBatches: 0,
      });
      eventSource.close();
    };

    return eventSource;
  },

  /**
   * Streams mood/energy/tempo/BPM analysis progress via SSE.
   * 
   * Uses Gemini AI to analyze songs based on metadata (artist, title, album, genre).
   * This approach leverages Gemini's knowledge of music styles rather than audio analysis.
   * Results are stored in the songs table for use by the AI DJ.
   * 
   * Analysis values:
   * - mood: happy, sad, energetic, calm, melancholic, uplifting, aggressive, romantic, chill, intense, dreamy, nostalgic
   * - energy: high, medium, low
   * - tempo: fast, medium, slow
   * - bpm: Estimated beats per minute (integer)
   * 
   * @param onProgress - Callback for progress updates with batch status
   * @returns EventSource instance (auto-closes on completion/error)
   */
  enrichMoodStream(
    onProgress: (progress: EnrichmentProgress) => void
  ): EventSource {
    const url = `${API_BASE}/library/enrich-mood/stream`;
    const eventSource = new EventSource(url);

    eventSource.onmessage = (event) => {
      try {
        const progress = JSON.parse(event.data) as EnrichmentProgress;
        onProgress(progress);
        
        // Auto-close on completion or error
        if (progress.status === 'complete' || progress.status === 'error') {
          eventSource.close();
        }
      } catch (e) {
        console.error('Failed to parse mood analysis progress:', e);
      }
    };

    eventSource.onerror = () => {
      onProgress({
        status: 'error',
        message: 'Connection lost',
        error: 'SSE connection failed',
        totalSongs: 0,
        processedSongs: 0,
        currentBatch: 0,
        totalBatches: 0,
      });
      eventSource.close();
    };

    return eventSource;
  },

  /**
   * Generate a smart playlist using the AI DJ feature.
   * 
   * The backend uses a three-tier matching system:
   * 1. Artist-based matching: For "more like [artist]" prompts
   * 2. Local genre matching: Direct match against indexed genres
   * 3. Gemini AI fallback: For complex prompts requiring AI interpretation
   * 
   * @param prompt - Natural language description of desired playlist
   * @param options.blendMode - 'single' for one genre, 'mixed' for multi-genre blending
   * @param options.targetSongs - Number of songs to return (default: 50, max: 100)
   * @param options.discoverMode - 'balanced', 'discover' (underplayed), or 'favorites'
   * @param options.avoidRecentlyHours - Exclude songs played within N hours (0 = off)
   * @param options.onePerArtist - Limit to one song per artist for variety
   * @param options.useTimeContext - Add time-of-day context to AI recommendations
   * @returns Playlist filter and matching songs
   */
  async generateSmartPlaylist(
    prompt: string, 
    options?: { 
      blendMode?: 'single' | 'mixed';
      targetSongs?: number;
      discoverMode?: 'balanced' | 'discover' | 'favorites';
      avoidRecentlyHours?: number;
      onePerArtist?: boolean;
      useTimeContext?: boolean;
    }
  ): Promise<SmartPlaylistResponse> {
    const response = await fetch(`${API_BASE}/smart-playlist`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        prompt,
        blendMode: options?.blendMode || 'single',
        targetSongs: options?.targetSongs || 50,
        discoverMode: options?.discoverMode || 'balanced',
        avoidRecentlyHours: options?.avoidRecentlyHours || 0,
        onePerArtist: options?.onePerArtist || false,
        useTimeContext: options?.useTimeContext || false,
      }),
    });
    return handleResponse(response);
  },
};

/**
 * Matched genre from AI DJ with scoring information.
 */
export interface MatchedGenre {
  name: string;
  score: number;
  songCount: number;
  proportion: number; // 0.0-1.0
}

/**
 * Smart playlist filter returned by AI DJ.
 */
export interface SmartPlaylistFilter {
  genres: string[];
  artists?: string[];
  minYear?: number;
  maxYear?: number;
  description?: string;
  mood?: string;
  energy?: string;
  tempo?: string;
  localMatch?: boolean;
  blendMode?: 'single' | 'mixed';
  matchedGenres?: MatchedGenre[];
}

/**
 * Response from the smart playlist API.
 */
export interface SmartPlaylistResponse {
  filter: SmartPlaylistFilter;
  songs: ApiSong[];
}

/**
 * Cached album metadata from the backend.
 * Used to persist Spotify lookup results and prevent redundant API calls.
 */
export interface ApiAlbumMetadata {
  albumKey: string;           // "{album}::{artist}" format
  albumName: string;
  artistName: string;
  spotifyId?: string;
  coverUrl?: string;          // Spotify artwork URL
  localCoverPath?: string;    // Local path to downloaded cover.jpg
  description?: string;
  genre?: string;
  releaseDate?: string;
  spotifyUrl?: string;
  copyright?: string;
  spotifyChecked: boolean;    // True if we've queried Spotify (even if not found)
  spotifyFound: boolean;      // True if Spotify returned results
  fetchedAt?: number;
  updatedAt?: number;
}

/**
 * Cached artist metadata from the backend.
 */
export interface ApiArtistMetadata {
  artistName: string;
  spotifyId?: string;
  imageUrl?: string;          // Spotify image URL
  localImagePath?: string;    // Local path to cached image
  spotifyUrl?: string;
  spotifyChecked: boolean;
  spotifyFound: boolean;
  fetchedAt?: number;
  updatedAt?: number;
}

export default api;
