// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataDir():Promise<string>;

export function GetServerURL():Promise<string>;

export function GetVersion():Promise<string>;

export function ShowWindow():Promise<void>;
