// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}
