/**
 * ViiB MediaHub - Spotify Track Helpers
 * 
 * Utility functions for converting Spotify API track data to Song objects
 * that can be played through the audio player.
 */

import { Song } from '../types';

/**
 * Converts a Spotify track object to a Song object for playback.
 * The song will use the streaming endpoint instead of a local file.
 * 
 * @param track - Spotify track data from Web API
 * @returns Song object ready for playback
 */
export function spotifyTrackToSong(track: {
    id: string;
    name: string;
    artists?: Array<{ name: string }>;
    album?: {
        name: string;
        images?: Array<{ url: string }>;
    };
    duration_ms: number;
}): Song {
    const artist = track.artists?.map(a => a.name).join(', ') || 'Unknown Artist';
    const album = track.album?.name || 'Unknown Album';
    const coverUrl = track.album?.images?.[0]?.url;

    return {
        id: `spotify:${track.id}`, // Prefix to distinguish from local songs
        title: track.name,
        artist,
        album,
        duration: Math.floor(track.duration_ms / 1000),
        url: '', // Will be generated by playerSlice when playing
        spotifyId: track.id,
        isStreaming: true,
        coverUrl,
        addedAt: Date.now(),
    };
}

/**
 * Converts an array of Spotify tracks to Song objects.
 * 
 * @param tracks - Array of Spotify track data
 * @returns Array of Song objects ready for playback
 */
export function spotifyTracksToSongs(tracks: Array<{
    id: string;
    name: string;
    artists?: Array<{ name: string }>;
    album?: {
        name: string;
        images?: Array<{ url: string }>;
    };
    duration_ms: number;
}>): Song[] {
    return tracks.filter(t => t && t.id).map(spotifyTrackToSong);
}

/**
 * Converts a Spotify album's tracks to Song objects.
 * Uses the album's artwork for all tracks.
 * 
 * @param album - Spotify album data with tracks
 * @returns Array of Song objects ready for playback
 */
export function spotifyAlbumToSongs(album: {
    name: string;
    artists?: Array<{ name: string }>;
    images?: Array<{ url: string }>;
    tracks?: {
        items: Array<{
            id: string;
            name: string;
            artists?: Array<{ name: string }>;
            duration_ms: number;
            track_number?: number;
            disc_number?: number;
        }>;
    };
}): Song[] {
    const albumArtist = album.artists?.map(a => a.name).join(', ') || 'Unknown Artist';
    const coverUrl = album.images?.[0]?.url;

    return (album.tracks?.items || []).filter(t => t && t.id).map(track => ({
        id: `spotify:${track.id}`,
        title: track.name,
        artist: track.artists?.map(a => a.name).join(', ') || albumArtist,
        album: album.name,
        albumArtist,
        trackNumber: track.track_number,
        discNumber: track.disc_number,
        duration: Math.floor(track.duration_ms / 1000),
        url: '',
        spotifyId: track.id,
        isStreaming: true,
        coverUrl,
        addedAt: Date.now(),
    }));
}
