// Package analysisbench provides Phase 0 fixtures and metadata used to compare
// audio-analysis candidates without coupling experimental code to the app.
package analysisbench

import (
	"fmt"
	"math"
)

// PCMFixture is deterministic interleaved PCM with an optional known tempo.
// It is intentionally small enough to be generated by tests and benchmarks.
type PCMFixture struct {
	Name       string
	Kind       string
	SampleRate int
	Channels   int
	Samples    []float32
	Expected   ExpectedAnalysis
}

// ExpectedAnalysis records only facts known by construction. It is not a
// substitute for a labeled real-world benchmark corpus.
type ExpectedAnalysis struct {
	BPM       *float64 `json:"bpm,omitempty"`
	TonicHz   *float64 `json:"tonicHz,omitempty"`
	Key       string   `json:"key,omitempty"`
	IsDynamic bool     `json:"isDynamic,omitempty"`
	IsUnknown bool     `json:"isUnknown"`
}

// Frames returns the number of PCM frames in the fixture.
func (f PCMFixture) Frames() int {
	if f.Channels == 0 {
		return 0
	}
	return len(f.Samples) / f.Channels
}

// DurationSeconds returns the fixture duration without importing time into
// callers that only need stable numeric benchmark metadata.
func (f PCMFixture) DurationSeconds() float64 {
	if f.SampleRate == 0 {
		return 0
	}
	return float64(f.Frames()) / float64(f.SampleRate)
}

// NewClickTrack creates a mono or multichannel click track with a known,
// fractional BPM. The click is a short decaying pulse, avoiding a degenerate
// one-sample impulse that can hide windowing bugs in candidate analyzers.
func NewClickTrack(name string, bpm, durationSeconds float64, sampleRate, channels int) (PCMFixture, error) {
	if name == "" {
		return PCMFixture{}, fmt.Errorf("fixture name is required")
	}
	if bpm <= 0 || durationSeconds <= 0 || sampleRate <= 0 || channels <= 0 {
		return PCMFixture{}, fmt.Errorf("bpm, duration, sample rate, and channels must be positive")
	}

	frames := int(math.Round(durationSeconds * float64(sampleRate)))
	samples := make([]float32, frames*channels)
	periodFrames := float64(sampleRate) * 60 / bpm
	clickFrames := max(1, int(math.Round(float64(sampleRate)*0.012)))

	for beat := 0; ; beat++ {
		start := int(math.Round(float64(beat) * periodFrames))
		if start >= frames {
			break
		}
		for offset := 0; offset < clickFrames && start+offset < frames; offset++ {
			envelope := math.Exp(-8 * float64(offset) / float64(clickFrames))
			value := float32(envelope * math.Sin(2*math.Pi*1000*float64(offset)/float64(sampleRate)))
			for channel := 0; channel < channels; channel++ {
				samples[(start+offset)*channels+channel] = value
			}
		}
	}

	return PCMFixture{
		Name:       name,
		Kind:       "click-track",
		SampleRate: sampleRate,
		Channels:   channels,
		Samples:    samples,
		Expected:   ExpectedAnalysis{BPM: &bpm},
	}, nil
}

// NewSineTone creates a sine fixture for chroma/tuning experiments.
func NewSineTone(name string, frequencyHz, durationSeconds float64, sampleRate, channels int) (PCMFixture, error) {
	if name == "" {
		return PCMFixture{}, fmt.Errorf("fixture name is required")
	}
	if frequencyHz <= 0 || durationSeconds <= 0 || sampleRate <= 0 || channels <= 0 {
		return PCMFixture{}, fmt.Errorf("frequency, duration, sample rate, and channels must be positive")
	}

	frames := int(math.Round(durationSeconds * float64(sampleRate)))
	samples := make([]float32, frames*channels)
	for frame := 0; frame < frames; frame++ {
		value := float32(0.5 * math.Sin(2*math.Pi*frequencyHz*float64(frame)/float64(sampleRate)))
		for channel := 0; channel < channels; channel++ {
			samples[frame*channels+channel] = value
		}
	}

	return PCMFixture{
		Name:       name,
		Kind:       "sine-tone",
		SampleRate: sampleRate,
		Channels:   channels,
		Samples:    samples,
		Expected:   ExpectedAnalysis{TonicHz: &frequencyHz},
	}, nil
}

// NewSilence creates an explicit no-result fixture. Production candidates must
// classify it as unknown rather than manufacturing a BPM or key.
func NewSilence(name string, durationSeconds float64, sampleRate, channels int) (PCMFixture, error) {
	if name == "" {
		return PCMFixture{}, fmt.Errorf("fixture name is required")
	}
	if durationSeconds <= 0 || sampleRate <= 0 || channels <= 0 {
		return PCMFixture{}, fmt.Errorf("duration, sample rate, and channels must be positive")
	}
	frames := int(math.Round(durationSeconds * float64(sampleRate)))
	return PCMFixture{
		Name:       name,
		Kind:       "silence",
		SampleRate: sampleRate,
		Channels:   channels,
		Samples:    make([]float32, frames*channels),
		Expected:   ExpectedAnalysis{IsUnknown: true},
	}, nil
}

// DefaultFixtures are stable smoke-test inputs. The required 200-track corpus
// remains an external Phase 0 deliverable and must not be conflated with these.
func DefaultFixtures() ([]PCMFixture, error) {
	click120, err := NewClickTrack("click-120", 120, 8, 44100, 2)
	if err != nil {
		return nil, err
	}
	click1285, err := NewClickTrack("click-128.5", 128.5, 8, 44100, 2)
	if err != nil {
		return nil, err
	}
	a4, err := NewSineTone("sine-a4", 440, 2, 44100, 2)
	if err != nil {
		return nil, err
	}
	silence, err := NewSilence("silence", 2, 44100, 2)
	if err != nil {
		return nil, err
	}
	return []PCMFixture{click120, click1285, a4, silence}, nil
}
